### ISSUE TITLE
Panic when querying block 35086755

### ISSUE THREAD

**Issue by alecalve** [algorand/indexer#1593]
### Subject of the issue

Command run:

```
$ curl http://localhost:8980/v2/blocks/35086755
curl: (52) Empty reply from server
```

Indexer logs:

```
panic: runtime error: index out of range [2] with length 2

goroutine 730 [running]:
github.com/algorand/indexer/v3/api.signedTxnWithAdToTransaction(_, {_, _, _, _, _})
	github.com/algorand/indexer/v3/api/converter_utils.go:529 +0x1d3a
github.com/algorand/indexer/v3/api.signedTxnWithAdToTransaction(_, {_, _, _, _, _})
	github.com/algorand/indexer/v3/api/converter_utils.go:574 +0x1385
github.com/algorand/indexer/v3/api.txnRowToTransaction({0x21761a3, {0x0, 0xedd2f7339, 0x0}, 0x0, 0xc000da2700, 0x0, 0x50ecec70, {0x0, {0x0, ...}, ...}, ...})
	github.com/algorand/indexer/v3/api/converter_utils.go:278 +0x26c
github.com/algorand/indexer/v3/api.(*ServerImplementation).fetchBlock.func1({0x1034648, 0xc00113b260})
	github.com/algorand/indexer/v3/api/handlers.go:1364 +0xea5
github.com/algorand/indexer/v3/api.callWithTimeout.func1({0x1034648?, 0xc00113b260?})
	github.com/algorand/indexer/v3/api/util.go:53 +0x3d
created by github.com/algorand/indexer/v3/api.callWithTimeout
	github.com/algorand/indexer/v3/api/util.go:52 +0x18d
```

### Your environment

- Algorand Indexer 3.4.0
- Algorand Node 3.21.0

I think the block in question was populated with a prior version of the indexer (3.3.0)

**Comment by urtho** [comment]
Blocks get populated by Conduit plugin (eg ver 1.6.0) , not indexer, which is now only an API. 

This is a bug in indexer-api 3.3.0 - can you double check if you are running 3.4.0 ? 
Can it be that you upgraded to conduit 1.6.0 but indexer-api is at 3.3.X ?

**Comment by urtho** [comment]
try  `curl http://localhost:8980/health` and check the version

**Comment by alecalve** [comment]
Indeed, I was mistakenly believing I was using 3.4.0 when I was using 3.3.0
