### ISSUE TITLE
Fix 'make e2e'

### ISSUE THREAD

**Issue by winder** [algorand/indexer#878]
### Subject of the issue

The e2e test is broken due to an incompatible private network archive. It needs to be regenerated.

These are the errors in node.log for the private network:
```
{"file":"node.go","function":"github.com/algorand/go-algorand/node.MakeFull","level":"error","line":207,"msg":"[Stack] goroutine 1 [running]:\nruntime/debug.Stack(0xc0004d67e0, 0xc000010540, 0xc0004c8460)\n\truntime/debug/stack.go:24 +0x9f\ngithub.com/algorand/go-algorand/logging.logger.Errorf(0xc0004d67e0, 0xc000010540, 0x1318b15, 0x21, 0xc003c8fb40, 0x2, 0x2)\n\tgithub.com/algorand/go-algorand/logging/log.go:229 +0x4a\ngithub.com/algorand/go-algorand/node.MakeFull(0x1a69880, 0xc0004869e0, 0x7ffe24d3be4a, 0x1c, 0x100000014, 0x1, 0xc00018fa92, 0xb, 0xdf8475800, 0x0, ...)\n\tgithub.com/algorand/go-algorand/node/node.go:207 +0xe8e\ngithub.com/algorand/go-algorand/daemon/algod.(*Server).Initialize(0xc00399fb38, 0x100000014, 0x1, 0xc00018fa92, 0xb, 0xdf8475800, 0x0, 0x0, 0x1e, 0x0, ...)\n\tgithub.com/algorand/go-algorand/daemon/algod/server.go:162 +0x903\nmain.run(0x0)\n\tgithub.com/algorand/go-algorand/cmd/algod/main.go:295 +0x1243\nmain.main()\n\tgithub.com/algorand/go-algorand/cmd/algod/main.go:61 +0x7b\n","time":"2022-02-12T21:03:08.018814Z"}
{"file":"node.go","function":"github.com/algorand/go-algorand/node.MakeFull","level":"error","line":207,"msg":"Cannot initialize ledger (/tmp/tmpme0qhssu/net/Primary/tbd-v1/ledger): reloadLedger.loadFromDisk votersTracker: underflow: 256 - 256 - 16 = 0","time":"2022-02-12T21:03:08.018983Z"}
{"file":"main.go","function":"main.run","level":"error","line":298,"msg":"[Stack] goroutine 1 [running]:\nruntime/debug.Stack(0xc0004d67e0, 0xc000010540, 0xc0004c87e0)\n\truntime/debug/stack.go:24 +0x9f\ngithub.com/algorand/go-algorand/logging.logger.Error(0xc0004d67e0, 0xc000010540, 0xc003cfc870, 0x1, 0x1)\n\tgithub.com/algorand/go-algorand/logging/log.go:219 +0x4a\nmain.run(0x0)\n\tgithub.com/algorand/go-algorand/cmd/algod/main.go:298 +0x134b\nmain.main()\n\tgithub.com/algorand/go-algorand/cmd/algod/main.go:61 +0x7b\n","time":"2022-02-12T21:03:08.019077Z"}
{"file":"main.go","function":"main.run","level":"error","line":298,"msg":"couldn't initialize the node: reloadLedger.loadFromDisk votersTracker: underflow: 256 - 256 - 16 = 0","time":"2022-02-12T21:03:08.019129Z"}
```

**Comment by winder** [comment]
This has been re-enabled.
